#ifndef TESTS_VERILATOR_SIM_UTIL_H_
#define TESTS_VERILATOR_SIM_UTIL_H_

#define CORALNPU_SIM_REPEAT_1(FN) FN(0)
#define CORALNPU_SIM_REPEAT_2(FN) CORALNPU_SIM_REPEAT_1(FN) FN(1)
#define CORALNPU_SIM_REPEAT_3(FN) CORALNPU_SIM_REPEAT_2(FN) FN(2)
#define CORALNPU_SIM_REPEAT_4(FN) CORALNPU_SIM_REPEAT_3(FN) FN(3)
#define CORALNPU_SIM_REPEAT_5(FN) CORALNPU_SIM_REPEAT_4(FN) FN(4)
#define CORALNPU_SIM_REPEAT_6(FN) CORALNPU_SIM_REPEAT_5(FN) FN(5)
#define CORALNPU_SIM_REPEAT_7(FN) CORALNPU_SIM_REPEAT_6(FN) FN(6)
#define CORALNPU_SIM_REPEAT_8(FN) CORALNPU_SIM_REPEAT_7(FN) FN(7)
#define CORALNPU_SIM_REPEAT_9(FN) CORALNPU_SIM_REPEAT_8(FN) FN(8)
#define CORALNPU_SIM_REPEAT_10(FN) CORALNPU_SIM_REPEAT_9(FN) FN(9)
#define CORALNPU_SIM_REPEAT_11(FN) CORALNPU_SIM_REPEAT_10(FN) FN(10)
#define CORALNPU_SIM_REPEAT_12(FN) CORALNPU_SIM_REPEAT_11(FN) FN(11)
#define CORALNPU_SIM_REPEAT_13(FN) CORALNPU_SIM_REPEAT_12(FN) FN(12)
#define CORALNPU_SIM_REPEAT_14(FN) CORALNPU_SIM_REPEAT_13(FN) FN(13)
#define CORALNPU_SIM_REPEAT_15(FN) CORALNPU_SIM_REPEAT_14(FN) FN(14)
#define CORALNPU_SIM_REPEAT_16(FN) CORALNPU_SIM_REPEAT_15(FN) FN(15)
#define CORALNPU_SIM_REPEAT_17(FN) CORALNPU_SIM_REPEAT_16(FN) FN(16)
#define CORALNPU_SIM_REPEAT(FN, N) CORALNPU_SIM_REPEAT_AUX(FN, N)
#define CORALNPU_SIM_REPEAT_AUX(FN, N) CORALNPU_SIM_REPEAT_##N(FN)

#define STRINGIFY(x) STRINGIFY_(x)
#define STRINGIFY_(x) #x

#endif  // TESTS_VERILATOR_SIM_UTIL_H_