#!/usr/bin/env python3
"""
Appends traceability metadata and LLM disclaimers to documentation files.
"""

import argparse
import os
import sys


def append_metadata(doc_dir, sha_file):
    """Appends the traceability footer to all .md files in the directory."""
    if not os.path.isfile(sha_file):
        print(f"Error: SHA file '{sha_file}' not found.")
        return False

    with open(sha_file, "r") as f:
        sha = f.read().strip()

    disclaimer = (
        "> ⚠️ **Disclaimer:** This document was generated or modified by an AI model. "
        "While every effort is made to ensure technical accuracy, the underlying "
        "source code and hardware RTL implementation remain the absolute source of truth. "
        "Use at your own risk.\n"
    )
    footer = f"\n> **Traceability:** Generated by Gemini. Derived from upstream commit {sha}.\n"

    count = 0
    for root, _, files in os.walk(doc_dir):
        for file in files:
            if file.endswith(".md"):
                file_path = os.path.join(root, file)
                with open(file_path, "r") as f:
                    content = f.read()

                # Check if metadata already exists to avoid duplication
                if f"Derived from upstream commit {sha}" in content:
                    continue

                # Prepare the new content
                new_lines = []
                if disclaimer not in content:
                    # Inject disclaimer at the top after license header if present
                    lines = content.splitlines(keepends=True)
                    in_header = False
                    inserted = False
                    for i, line in enumerate(lines):
                        if "<!--" in line:
                            in_header = True
                        if "-->" in line:
                            in_header = False
                            new_lines.extend(lines[: i + 1])
                            new_lines.append("\n")
                            new_lines.append(disclaimer)
                            new_lines.extend(lines[i + 1 :])
                            inserted = True
                            break
                    
                    if not inserted:
                        new_lines.append(disclaimer)
                        new_lines.append("\n")
                        new_lines.extend(lines)
                else:
                    new_lines = [content]

                final_content = "".join(new_lines)
                if footer not in final_content:
                    if not final_content.endswith("\n"):
                        final_content += "\n"
                    final_content += footer

                with open(file_path, "w") as f:
                    f.write(final_content)
                count += 1

    print(f"Updated {count} files with metadata.")
    return True


def main():
    parser = argparse.ArgumentParser(description="Append metadata to documentation.")
    parser.add_argument("--doc-dir", default="doc", help="Directory containing documentation")
    parser.add_argument("--sha-file", default="/tmp/doc_upstream_sha_julianmb.txt", help="File containing the upstream SHA")
    args = parser.parse_args()

    if not append_metadata(args.doc_dir, args.sha_file):
        sys.exit(1)


if __name__ == "__main__":
    main()
