#!/usr/bin/env python3

def inject_traceability_footer(content, sha):
    footer = f"\n\n> **Traceability:** Generated by Gemini. Derived from upstream commit {sha}."
    if footer in content:
        return content
    # Remove any existing footer if it's inconsistent (simple check)
    lines = content.split('\n')
    new_lines = []
    for line in lines:
        if not line.startswith('> **Traceability:**'):
            new_lines.append(line)
    content = '\n'.join(new_lines)
    return content + footer

def inject_llm_disclaimer(content):
    disclaimer = "> ⚠️ **Disclaimer:** This document was generated or modified by an AI model. While every effort is made to ensure technical accuracy, the underlying source code and hardware RTL implementation remain the absolute source of truth. Use at your own risk.\n\n"
    if disclaimer in content:
        return content
    # Remove any existing disclaimer if it's inconsistent (simple check)
    lines = content.split('\n')
    new_lines = []
    for line in lines:
        if not line.startswith('> ⚠️ **Disclaimer:**'):
            new_lines.append(line)
        else:
            # Skip the disclaimer line
            continue
    content = '\n'.join(new_lines)
    return disclaimer + content

if __name__ == '__main__':
    import sys
    # Basic CLI usage for the script
    if len(sys.argv) < 3:
        print("Usage: inject_metadata.py <file> <sha>")
        sys.exit(1)
    
    file_path = sys.argv[1]
    sha = sys.argv[2]
    
    with open(file_path, 'r') as f:
        content = f.read()
    
    # Inject metadata
    content = inject_llm_disclaimer(content)
    content = inject_traceability_footer(content, sha)
    
    with open(file_path, 'w') as f:
        f.write(content)
