#!/usr/bin/env python3
"""
Unit tests for append_doc_metadata.py.
"""

import os
import shutil
import sys
import tempfile
import unittest

# Add scripts directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../scripts")))
import append_doc_metadata


class TestAppendDocMetadata(unittest.TestCase):

    def setUp(self):
        self.test_dir = tempfile.mkdtemp()
        self.doc_dir = os.path.join(self.test_dir, "doc")
        os.makedirs(self.doc_dir)
        self.sha_file = os.path.join(self.test_dir, "sha.txt")
        self.sha_val = "1234567890abcdef"
        with open(self.sha_file, "w") as f:
            f.write(self.sha_val)

    def tearDown(self):
        shutil.rmtree(self.test_dir)

    def test_append_basic(self):
        """Verifies basic metadata appending."""
        test_file = os.path.join(self.doc_dir, "test.md")
        with open(test_file, "w") as f:
            f.write("# Test Document\n\nSome content.")

        append_doc_metadata.append_metadata(self.doc_dir, self.sha_file)

        with open(test_file, "r") as f:
            content = f.read()

        self.assertIn("> ⚠️ **Disclaimer:**", content)
        self.assertIn(f"> **Traceability:** Generated by Gemini. Derived from upstream commit {self.sha_val}.", content)

    def test_append_with_header(self):
        """Verifies appending after a license header."""
        test_file = os.path.join(self.doc_dir, "header.md")
        header = "<!--\n License Header\n-->\n"
        body = "# Title\nContent"
        with open(test_file, "w") as f:
            f.write(header + body)

        append_doc_metadata.append_metadata(self.doc_dir, self.sha_file)

        with open(test_file, "r") as f:
            content = f.read()

        self.assertTrue(content.startswith(header))
        self.assertIn("> ⚠️ **Disclaimer:**", content)
        # Disclaimer should be after header
        self.assertTrue(content.index("> ⚠️ **Disclaimer:**") > content.index("-->"))

    def test_idempotency(self):
        """Verifies that the script is idempotent."""
        test_file = os.path.join(self.doc_dir, "idem.md")
        with open(test_file, "w") as f:
            f.write("# Idem\nContent")

        append_doc_metadata.append_metadata(self.doc_dir, self.sha_file)
        with open(test_file, "r") as f:
            first_content = f.read()

        append_doc_metadata.append_metadata(self.doc_dir, self.sha_file)
        with open(test_file, "r") as f:
            second_content = f.read()

        self.assertEqual(first_content, second_content)
        self.assertEqual(second_content.count("> ⚠️ **Disclaimer:**"), 1)
        self.assertEqual(second_content.count("> **Traceability:**"), 1)


if __name__ == "__main__":
    unittest.main()
